version: "3"

services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/${PRISMA_SERVICE}/${PRISMA_STAGE}
      JWT_SECRET: ${JWT_SECRET}
      PRISMA_SERVICE: ${PRISMA_SERVICE}
      PRISMA_STAGE: ${PRISMA_STAGE}
    command: npm run dev
    volumes:
      - .:/usr/app

  prisma:
    image: prismagraphql/prisma:1.28
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    networks:
      - postgres-network

  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "prisma"
      POSTGRES_PASSWORD: "Postgres2019!"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "anapf9@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

volumes:
  postgres:

networks:
  postgres-network:
    driver: bridge
